/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * adminvendedor.java
 *
 * Created on Oct 27, 2009, 6:56:01 PM
 */

package presentacion;

import java.awt.Color;
import entidad.Usuario;
import entidad.Puntodeventa;
import control.RegistrarVendedor;
import control.RegistrarPuntoVenta;
import entidad.Rol;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.Iterator;

/**
 *
 * @author alirio
 */
public class PAdminvendedor extends javax.swing.JFrame {

    private PAdministrador parent;
    private List registrosUsuario;
    private int posicion = 0;
    private Usuario usuarioActual;
    private List<Puntodeventa> listaPuntoVenta;
    private boolean editando;

    /** Creates new form adminvendedor */
    public PAdminvendedor(PAdministrador parent)
    {

        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        this.parent=parent;
        cargarPuntosDeVenta();
        editando = false;
        jButtonEditar.setVisible(false);
        jButtonEditar.setVisible(false);
        jButtonRegistrar.setVisible(true);
        jButtonEliminar.setVisible(false);
    }

    private void cargarPuntosDeVenta()
    {
        Iterator lIterator = null;
        Puntodeventa lPuntodeVenta = null;
        RegistrarPuntoVenta lRegistrarPuntoVenta = new RegistrarPuntoVenta();
        listaPuntoVenta = lRegistrarPuntoVenta.getPuntosDeVenta();
        if( listaPuntoVenta != null && !listaPuntoVenta.isEmpty() )
        {
            lIterator = listaPuntoVenta.iterator();
            while( lIterator.hasNext() )
            {
               lPuntodeVenta = ( Puntodeventa ) lIterator.next();
               jComboBoxPuntoVenta.addItem(lPuntodeVenta.getNombre());

            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelRegistrar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextNombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextDireccion = new javax.swing.JTextField();
        Cedula = new javax.swing.JLabel();
        jTextCedula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerEdad = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordClave = new javax.swing.JPasswordField();
        jComboBoxPuntoVenta = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jCheckBoxActivo = new javax.swing.JCheckBox();
        jButtonEditar = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        jPanelEliminar = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTextValorBusquedaEliminar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButtonBuscarEliminar = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jRadioFiltroCedularEliminar = new javax.swing.JRadioButton();
        jRadioNombreEliminar = new javax.swing.JRadioButton();
        jPanel12 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrar Vendedores");
        setBackground(new java.awt.Color(244, 139, 33));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrar vendedores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        jPanelRegistrar.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 3, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setText("Nombres:");

        jLabel2.setText("Apellidos");

        jLabel3.setText("Telefono:");

        jLabel4.setText("Direccion:");

        Cedula.setText("Cedula");

        jLabel6.setText("edad:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextCedula, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jTextNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addComponent(Cedula))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jTextApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(jTextDireccion))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cedula)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Sistema", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 3, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel7.setText("Usuario:");

        jLabel8.setText("Contraseña:");

        jLabel9.setText("Punto de Venta:");

        jCheckBoxActivo.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxActivo.setText("Activar/Desactivar vendedor");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jPasswordClave)
                    .addComponent(jTextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jComboBoxPuntoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jCheckBoxActivo)))
                .addGap(29, 29, 29))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxActivo)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxPuntoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/save.gif"))); // NOI18N
        jButtonEditar.setText("Guardar cambios");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/edit.gif"))); // NOI18N
        jButtonRegistrar.setText("Registrar Vendedor");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/load.gif"))); // NOI18N
        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegistrarLayout = new javax.swing.GroupLayout(jPanelRegistrar);
        jPanelRegistrar.setLayout(jPanelRegistrarLayout);
        jPanelRegistrarLayout.setHorizontalGroup(
            jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistrarLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistrarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRegistrar))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );
        jPanelRegistrarLayout.setVerticalGroup(
            jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editar)
                    .addComponent(jButtonRegistrar)
                    .addComponent(jButtonEditar))
                .addGap(19, 19, 19))
        );

        jTabbedPane.addTab("Registrar", jPanelRegistrar);

        jPanelEliminar.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda Vendedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 3, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel13.setText("Buscar Por:");

        jButtonBuscarEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/search.gif"))); // NOI18N
        jButtonBuscarEliminar.setText("Buscar.");
        jButtonBuscarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarEliminarActionPerformed(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jRadioFiltroCedularEliminar.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioFiltroCedularEliminar);
        jRadioFiltroCedularEliminar.setText("Cedula");

        jRadioNombreEliminar.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioNombreEliminar);
        jRadioNombreEliminar.setText("Nombre");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioFiltroCedularEliminar)
                .addGap(30, 30, 30)
                .addComponent(jRadioNombreEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioFiltroCedularEliminar)
                .addComponent(jRadioNombreEliminar))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextValorBusquedaEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jButtonBuscarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextValorBusquedaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonBuscarEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/deleteall.gif"))); // NOI18N
        jButton5.setText("Eliminar Vendedor");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/eliminar.gif"))); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(jButtonEliminar)
                .addGap(30, 30, 30)
                .addComponent(jButton5)
                .addGap(69, 69, 69))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButtonEliminar))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout jPanelEliminarLayout = new javax.swing.GroupLayout(jPanelEliminar);
        jPanelEliminar.setLayout(jPanelEliminarLayout);
        jPanelEliminarLayout.setHorizontalGroup(
            jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(jPanelEliminarLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(112, 112, 112))
        );
        jPanelEliminarLayout.setVerticalGroup(
            jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Eliminar", jPanelEliminar);

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/salir.gif"))); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salir)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private Usuario obtenerDatos()
    {
        Usuario lUsuario = new Usuario();
        Puntodeventa lPuntodeventa = new Puntodeventa();
        Rol lRol = new Rol();

        lUsuario.setNombres( jTextNombres.getText() );
        lUsuario.setApellidos(jTextApellidos.getText());
        lUsuario.setDireccion( jTextDireccion.getText() );
        lUsuario.setTelefono( jTextTelefono.getText() );
        lUsuario.setCedula( jTextCedula.getText());
        lUsuario.setUsuario(jTextUsuario.getText());
        //if (!jPasswordClave.getText().isEmpty())
            lUsuario.setContrasena(jPasswordClave.getText());
        lUsuario.setActivo(jCheckBoxActivo.isSelected());
        lPuntodeventa.setId( listaPuntoVenta.get(jComboBoxPuntoVenta.getSelectedIndex()).getId());
        lUsuario.setFkPuntodeventa(lPuntodeventa);
        lRol.setId(2);
        lUsuario.setFkRol(lRol);

        return lUsuario;

    }

    private void presentarMensaje( String pMensaje, String pTitulo )
    {
        JOptionPane.showMessageDialog(this, pMensaje, pTitulo, JOptionPane.DEFAULT_OPTION);
        
    }

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        parent.setVisible(true);
    }//GEN-LAST:event_salirActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
         Usuario lUsuario = new Usuario();
        lUsuario = obtenerDatos();
        RegistrarVendedor lRegistrarVendedor = new RegistrarVendedor();

        try
        {
            lRegistrarVendedor.registrarVendedor(lUsuario);
            presentarMensaje("El usuario " + lUsuario.getUsuario() + " fue creado con exito"  ,
                             "Mensaje de exito" );
            usuarioActual = new Usuario();
            presentarUsuario(usuarioActual);

        }
        catch( Exception pException )
        {
            presentarMensaje( pException.getMessage(),"Mensaje de error" );
        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void presentarUsuario( Usuario pUsuario )
    {
        jTextNombres.setText(pUsuario.getNombres(  ));
        jTextApellidos.setText(pUsuario.getApellidos());
        jTextDireccion.setText(pUsuario.getDireccion());
        jTextTelefono.setText(pUsuario.getTelefono( ));
        jTextCedula.setText(pUsuario.getCedula());
        jTextUsuario.setText(pUsuario.getUsuario());
        jPasswordClave.setText(pUsuario.getContrasena());
        jCheckBoxActivo.setSelected(pUsuario.getActivo());
        if( pUsuario.getFkPuntodeventa() != null )
        {
            jComboBoxPuntoVenta.setSelectedItem( pUsuario.getFkPuntodeventa().getId() );
        }
        jPanelRegistrar.setVisible(true);
        jPanelRegistrar.updateUI();
        jPanelEliminar.setVisible(false);
    }

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        Usuario lUsuarioModificado = null;
        lUsuarioModificado = obtenerDatos();
        lUsuarioModificado.setId(  usuarioActual.getId() );
        lUsuarioModificado.setRegistroventaList(usuarioActual.getRegistroventaList());

         RegistrarVendedor lRegistrarVendedor = new RegistrarVendedor();

        try
        {
            lRegistrarVendedor.modificarVendedor(lUsuarioModificado);
            presentarMensaje("El usuario " + lUsuarioModificado.getUsuario() + " fue modificado con exito"  ,
                             "Mensaje de exito" );
            usuarioActual = new Usuario();
            presentarUsuario(usuarioActual);
            jButtonRegistrar.setEnabled(true);
            editando = false;
            jButtonEditar.setVisible(false);
        }
        catch( Exception pException )
        {
            pException.printStackTrace();
            presentarMensaje( pException.getMessage(),"Mensaje de error" );
        }       
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonBuscarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarEliminarActionPerformed
        // TODO add your handling code here:
         String lCampoFiltro = null;
        String lValorFiltro = null;
        RegistrarVendedor lRegistrarVendedor;
        posicion = 0;
        this.jButtonEditar.setVisible(false);
        this.jButtonRegistrar.setVisible(true);
        this.jButtonEliminar.setVisible(false);

        try
        {
            if( this.jRadioFiltroCedularEliminar.isSelected() )
            {
                lCampoFiltro = "Cedula";
            }
            else if( this.jRadioNombreEliminar.isSelected() )
            {
                lCampoFiltro = "Nombre";
            }

            lValorFiltro = jTextValorBusquedaEliminar.getText();
            lRegistrarVendedor = new RegistrarVendedor();
            registrosUsuario = lRegistrarVendedor.obtenerVendedores(lCampoFiltro, lValorFiltro);
            if( registrosUsuario == null || registrosUsuario.isEmpty() )
            {
                this.presentarMensaje("No se enctraron registros", "Mensaje de aviso");
            }
            else
            {
                    usuarioActual = ( Usuario ) registrosUsuario.get(posicion);
                    jButtonEliminar.setVisible(true);
                    presentarUsuario(usuarioActual);
                    repaint();
            }
        }
        catch( Exception pException )
        {
             this.presentarMensaje( pException.getMessage(), "Mensaje de aviso");
        }

    }//GEN-LAST:event_jButtonBuscarEliminarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        Usuario lUsuarioModificado = null;
        lUsuarioModificado = obtenerDatos();
        lUsuarioModificado.setId(  usuarioActual.getId() );
        lUsuarioModificado.setRegistroventaList(usuarioActual.getRegistroventaList());

        RegistrarVendedor lRegistrarVendedor = new RegistrarVendedor();

        try
        {
            lRegistrarVendedor.eliminarVendedor(lUsuarioModificado);
            presentarMensaje("El usuario " + lUsuarioModificado.getUsuario() + " fue eliminado con exito"  ,
                             "Mensaje de exito" );
            usuarioActual = new Usuario();
            presentarUsuario(usuarioActual);
        }
        catch( Exception pException )
        {
           pException.printStackTrace();
            presentarMensaje( pException.getMessage(),"Mensaje de error" );
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        PCargaVendedoresDialogo carga = new PCargaVendedoresDialogo(this, true);
        carga.setLocationRelativeTo(null);
        carga.setVisible(true);
        if(usuarioActual != null){
            editando = true;
            jButtonRegistrar.setEnabled(false);
            jButtonEditar.setVisible(true);
            presentarUsuario(usuarioActual);
        }
    }//GEN-LAST:event_editarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cedula;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton editar;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonBuscarEliminar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JCheckBox jCheckBoxActivo;
    private javax.swing.JComboBox jComboBoxPuntoVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelEliminar;
    private javax.swing.JPanel jPanelRegistrar;
    private javax.swing.JPasswordField jPasswordClave;
    private javax.swing.JRadioButton jRadioFiltroCedularEliminar;
    private javax.swing.JRadioButton jRadioNombreEliminar;
    private javax.swing.JSpinner jSpinnerEdad;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextField jTextApellidos;
    private javax.swing.JTextField jTextCedula;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextNombres;
    private javax.swing.JTextField jTextTelefono;
    private javax.swing.JTextField jTextUsuario;
    private javax.swing.JTextField jTextValorBusquedaEliminar;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables

    public void setUsuarioActual(Usuario usuarioActual) {
        this.usuarioActual = usuarioActual;
    }

    
}
