/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * adminescenario.java
 *
 * Created on Oct 27, 2009, 9:10:00 PM
 */

package presentacion;

import java.awt.Color;
import entidad.Escenario;
import control.AdministrarEscenario;
import java.awt.Component;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.List;

/**
 *
 * @author alirio
 */
public class PAdminescenario extends javax.swing.JFrame {

    private PAdministrador parent;
    private int posicion, posicion2;
    List registrosEscenario = null;




    /** Creates new form adminescenario */
    public PAdminescenario(PAdministrador parent) {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        this.parent=parent;
        this.BoxCiudad.addItem("Bogota");
        this.BoxCiudad.addItem("Medellin");
        this.BoxCiudad.addItem("Cali");
        this.BoxCiudad.addItem("Barranquilla");
        this.BoxCiudad.addItem("Bucaramanga");
        this.BoxCiudad.addItem("Cartagena");
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelRegistrarEscenario = new javax.swing.JPanel();
        jPanelAspectosGenerales = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NombreEscenario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BoxCiudad = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        DireccionEscenario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TelefonoEscenario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FieldMapa = new javax.swing.JTextField();
        jButtonRegistrarEscenario = new javax.swing.JButton();
        jPanelEditarEscenario = new javax.swing.JPanel();
        jPanelBusquedaEditar = new javax.swing.JPanel();
        Busqueda = new javax.swing.JTextField();
        jButtonBuscarEditarEscenario = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanelAspectosGenerales1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        NombreEscenario1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BoxCiudad1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        DireccionEscenario1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TelefonoEscenario1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        FieldMapa1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanelEliminarEscenario = new javax.swing.JPanel();
        jPanelBusquedaEliminar = new javax.swing.JPanel();
        Eliminar = new javax.swing.JTextField();
        jButtonBuscarEliminar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanelAspectosGenerales2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        NombreEscenario2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        BoxCiudad2 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        DireccionEscenario2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TelefonoEscenario2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        FieldMapa2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrar Escenario");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrar escenarios", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 13), new java.awt.Color(51, 51, 51))); // NOI18N

        jPanelRegistrarEscenario.setBackground(new java.awt.Color(255, 255, 255));

        jPanelAspectosGenerales.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAspectosGenerales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aspectos Generales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 3, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setText("Nombre:");

        jLabel2.setText("Mapa");

        jLabel3.setText("Direccion");

        jLabel4.setText("Telefono:");

        jLabel5.setText("Ciudad:");

        javax.swing.GroupLayout jPanelAspectosGeneralesLayout = new javax.swing.GroupLayout(jPanelAspectosGenerales);
        jPanelAspectosGenerales.setLayout(jPanelAspectosGeneralesLayout);
        jPanelAspectosGeneralesLayout.setHorizontalGroup(
            jPanelAspectosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAspectosGeneralesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelAspectosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(NombreEscenario, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAspectosGeneralesLayout.createSequentialGroup()
                        .addGroup(jPanelAspectosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAspectosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TelefonoEscenario, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DireccionEscenario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanelAspectosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanelAspectosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(BoxCiudad, 0, 218, Short.MAX_VALUE)
                                .addComponent(FieldMapa)))))
                .addContainerGap())
        );
        jPanelAspectosGeneralesLayout.setVerticalGroup(
            jPanelAspectosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAspectosGeneralesLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreEscenario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelAspectosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAspectosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DireccionEscenario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanelAspectosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAspectosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefonoEscenario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButtonRegistrarEscenario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/register.gif"))); // NOI18N
        jButtonRegistrarEscenario.setText("Registrar Escenario");
        jButtonRegistrarEscenario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarEscenarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegistrarEscenarioLayout = new javax.swing.GroupLayout(jPanelRegistrarEscenario);
        jPanelRegistrarEscenario.setLayout(jPanelRegistrarEscenarioLayout);
        jPanelRegistrarEscenarioLayout.setHorizontalGroup(
            jPanelRegistrarEscenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrarEscenarioLayout.createSequentialGroup()
                .addGroup(jPanelRegistrarEscenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistrarEscenarioLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanelAspectosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRegistrarEscenarioLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jButtonRegistrarEscenario)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanelRegistrarEscenarioLayout.setVerticalGroup(
            jPanelRegistrarEscenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrarEscenarioLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanelAspectosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRegistrarEscenario)
                .addGap(116, 116, 116))
        );

        jTabbedPane1.addTab("Registrar", jPanelRegistrarEscenario);

        jPanelEditarEscenario.setBackground(new java.awt.Color(255, 255, 255));

        jPanelBusquedaEditar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBusquedaEditar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda Escenario:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 3, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        jButtonBuscarEditarEscenario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/search.gif"))); // NOI18N
        jButtonBuscarEditarEscenario.setText("Buscar.");
        jButtonBuscarEditarEscenario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarEditarEscenarioActionPerformed(evt);
            }
        });

        jLabel12.setText("Digite su busqueda en minusculas");

        javax.swing.GroupLayout jPanelBusquedaEditarLayout = new javax.swing.GroupLayout(jPanelBusquedaEditar);
        jPanelBusquedaEditar.setLayout(jPanelBusquedaEditarLayout);
        jPanelBusquedaEditarLayout.setHorizontalGroup(
            jPanelBusquedaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBusquedaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Busqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(jPanelBusquedaEditarLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jButtonBuscarEditarEscenario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelBusquedaEditarLayout.setVerticalGroup(
            jPanelBusquedaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanelBusquedaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscarEditarEscenario)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAspectosGenerales1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAspectosGenerales1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aspectos Generales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 3, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel6.setText("Nombre:");

        jLabel7.setText("Mapa");

        jLabel8.setText("Direccion");

        jLabel9.setText("Telefono:");

        jLabel10.setText("Ciudad:");

        javax.swing.GroupLayout jPanelAspectosGenerales1Layout = new javax.swing.GroupLayout(jPanelAspectosGenerales1);
        jPanelAspectosGenerales1.setLayout(jPanelAspectosGenerales1Layout);
        jPanelAspectosGenerales1Layout.setHorizontalGroup(
            jPanelAspectosGenerales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAspectosGenerales1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelAspectosGenerales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(NombreEscenario1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAspectosGenerales1Layout.createSequentialGroup()
                        .addGroup(jPanelAspectosGenerales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAspectosGenerales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TelefonoEscenario1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DireccionEscenario1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanelAspectosGenerales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanelAspectosGenerales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addComponent(BoxCiudad1, 0, 218, Short.MAX_VALUE)
                                .addComponent(FieldMapa1)))))
                .addContainerGap())
        );
        jPanelAspectosGenerales1Layout.setVerticalGroup(
            jPanelAspectosGenerales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAspectosGenerales1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreEscenario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelAspectosGenerales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAspectosGenerales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DireccionEscenario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldMapa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanelAspectosGenerales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAspectosGenerales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefonoEscenario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxCiudad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/edit.gif"))); // NOI18N
        jButton1.setText("Editar Escenario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEditarEscenarioLayout = new javax.swing.GroupLayout(jPanelEditarEscenario);
        jPanelEditarEscenario.setLayout(jPanelEditarEscenarioLayout);
        jPanelEditarEscenarioLayout.setHorizontalGroup(
            jPanelEditarEscenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarEscenarioLayout.createSequentialGroup()
                .addGroup(jPanelEditarEscenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEditarEscenarioLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jPanelBusquedaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEditarEscenarioLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanelAspectosGenerales1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEditarEscenarioLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jButton1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanelEditarEscenarioLayout.setVerticalGroup(
            jPanelEditarEscenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarEscenarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBusquedaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanelAspectosGenerales1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Editar", jPanelEditarEscenario);

        jPanelEliminarEscenario.setBackground(new java.awt.Color(255, 255, 255));

        jPanelBusquedaEliminar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBusquedaEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda Escenario:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 3, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        jButtonBuscarEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/search.gif"))); // NOI18N
        jButtonBuscarEliminar.setText("Buscar");
        jButtonBuscarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarEliminarActionPerformed(evt);
            }
        });

        jLabel13.setText("Digite su busqueda en minusculas");

        javax.swing.GroupLayout jPanelBusquedaEliminarLayout = new javax.swing.GroupLayout(jPanelBusquedaEliminar);
        jPanelBusquedaEliminar.setLayout(jPanelBusquedaEliminarLayout);
        jPanelBusquedaEliminarLayout.setHorizontalGroup(
            jPanelBusquedaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBusquedaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addGroup(jPanelBusquedaEliminarLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscarEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelBusquedaEliminarLayout.setVerticalGroup(
            jPanelBusquedaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBusquedaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscarEliminar)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAspectosGenerales2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAspectosGenerales2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aspectos Generales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 3, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel11.setText("Nombre:");

        jLabel14.setText("Mapa");

        jLabel15.setText("Direccion");

        jLabel16.setText("Telefono:");

        jLabel17.setText("Ciudad:");

        javax.swing.GroupLayout jPanelAspectosGenerales2Layout = new javax.swing.GroupLayout(jPanelAspectosGenerales2);
        jPanelAspectosGenerales2.setLayout(jPanelAspectosGenerales2Layout);
        jPanelAspectosGenerales2Layout.setHorizontalGroup(
            jPanelAspectosGenerales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAspectosGenerales2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelAspectosGenerales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(NombreEscenario2, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAspectosGenerales2Layout.createSequentialGroup()
                        .addGroup(jPanelAspectosGenerales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAspectosGenerales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TelefonoEscenario2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DireccionEscenario2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanelAspectosGenerales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(jPanelAspectosGenerales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel14)
                                .addComponent(BoxCiudad2, 0, 218, Short.MAX_VALUE)
                                .addComponent(FieldMapa2)))))
                .addContainerGap())
        );
        jPanelAspectosGenerales2Layout.setVerticalGroup(
            jPanelAspectosGenerales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAspectosGenerales2Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreEscenario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelAspectosGenerales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAspectosGenerales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DireccionEscenario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldMapa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanelAspectosGenerales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAspectosGenerales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefonoEscenario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxCiudad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/eliminar.gif"))); // NOI18N
        jButton2.setText("Eliminar Escenario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEliminarEscenarioLayout = new javax.swing.GroupLayout(jPanelEliminarEscenario);
        jPanelEliminarEscenario.setLayout(jPanelEliminarEscenarioLayout);
        jPanelEliminarEscenarioLayout.setHorizontalGroup(
            jPanelEliminarEscenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarEscenarioLayout.createSequentialGroup()
                .addGroup(jPanelEliminarEscenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEliminarEscenarioLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanelAspectosGenerales2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEliminarEscenarioLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jButton2))
                    .addGroup(jPanelEliminarEscenarioLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jPanelBusquedaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanelEliminarEscenarioLayout.setVerticalGroup(
            jPanelEliminarEscenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarEscenarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBusquedaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAspectosGenerales2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPanelEliminarEscenario);

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/salir.gif"))); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        parent.setVisible(true);
    }//GEN-LAST:event_salirActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosed



    private void jButtonRegistrarEscenarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarEscenarioActionPerformed

        if(NombreEscenario.getText().equals("") || DireccionEscenario.getText().equals("") ||
                TelefonoEscenario.getText().equals("") || FieldMapa.getText().equals("")){
            JOptionPane.showMessageDialog((Component)null,
				"Ningun campo puede estar vacio!!", "error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            AdministrarEscenario admin = new AdministrarEscenario();
            try {
                admin.registrarEscenario(NombreEscenario.getText(),  DireccionEscenario.getText(),
                        FieldMapa.getText(),TelefonoEscenario.getText(), BoxCiudad.getSelectedItem().toString());
                JOptionPane.showMessageDialog((Component)null,
				"El escenario fue registrado Con exito!!", "Exito",JOptionPane.INFORMATION_MESSAGE);

                NombreEscenario.setText("");
                DireccionEscenario.setText("");
                TelefonoEscenario.setText("");
                FieldMapa.setText("");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog((Component)null,
				"Ocurrio un error en la creacion del escenario", "Error",JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(PAdminescenario.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


            
    }//GEN-LAST:event_jButtonRegistrarEscenarioActionPerformed

private void jButtonBuscarEditarEscenarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarEditarEscenarioActionPerformed
    // TODO add your handling code here:

    String nombre = Busqueda.getText();
    AdministrarEscenario admin = new AdministrarEscenario();
     List<String> lista = new ArrayList<String>();
    lista = admin.Buscar(nombre);
    if(lista !=null){
        posicion=0;
        posicion = Integer.parseInt(lista.get(0));
        NombreEscenario1.setText(lista.get(1));
        BoxCiudad1.addItem(lista.get(2));
        DireccionEscenario1.setText(lista.get(3));
        TelefonoEscenario1.setText(lista.get(4));
        FieldMapa1.setText(lista.get(5));
        jButton1.setEnabled(true);
   }
    else{
        JOptionPane.showMessageDialog((Component)null,
				"el evento indicado no existe!!1", "Error",JOptionPane.ERROR_MESSAGE);
        NombreEscenario1.setText("");
        BoxCiudad1.removeAllItems();
        DireccionEscenario1.setText("");
        TelefonoEscenario1.setText("");
        FieldMapa1.setText("");
        jButton1.setEnabled(false);
    }



}//GEN-LAST:event_jButtonBuscarEditarEscenarioActionPerformed

private void jButtonBuscarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarEliminarActionPerformed
    // TODO add your handling code here:

    String nombre = Eliminar.getText();
    AdministrarEscenario admin = new AdministrarEscenario();
     List<String> lista = new ArrayList<String>();
    lista = admin.Buscar(nombre);
    if(lista !=null){
        posicion2=0;
        posicion2 = Integer.parseInt(lista.get(0));
        NombreEscenario2.setText(lista.get(1));
        BoxCiudad2.addItem(lista.get(2));
        DireccionEscenario2.setText(lista.get(3));
        TelefonoEscenario2.setText(lista.get(4));
        FieldMapa2.setText(lista.get(5));
        jButton2.setEnabled(true);
   }
    else{
        JOptionPane.showMessageDialog((Component)null,
				"el evento indicado no existe!!1", "Error",JOptionPane.ERROR_MESSAGE);
        NombreEscenario2.setText("");
        BoxCiudad2.removeAllItems();
        DireccionEscenario2.setText("");
        TelefonoEscenario2.setText("");
        FieldMapa2.setText("");
        jButton2.setEnabled(false);
    }



}//GEN-LAST:event_jButtonBuscarEliminarActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:

        int ans =  JOptionPane.showConfirmDialog((Component)null,"¿Esta seguro de que desea eliminar este escenario?", "Confirmacion",JOptionPane.YES_NO_OPTION);
        if (ans == JOptionPane.YES_OPTION) {
            AdministrarEscenario admin = new AdministrarEscenario();
                try {
                    int a = admin.eliminarEscenario(posicion2);
                    if(a==0){
                        JOptionPane.showMessageDialog((Component)null,
                                    "el escenario fue eliminado", "Exito",JOptionPane.INFORMATION_MESSAGE);
                        NombreEscenario2.setText("");
                        BoxCiudad2.removeAllItems();
                        DireccionEscenario2.setText("");
                        TelefonoEscenario2.setText("");
                        FieldMapa2.setText("");
                        jButton2.setEnabled(false);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(PAdminescenario.class.getName()).log(Level.SEVERE, null, ex);
                }
        }

}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:

     AdministrarEscenario admin = new AdministrarEscenario();
        try {
            admin.modificarEscenario(posicion, NombreEscenario1.getText(), DireccionEscenario1.getText(),
                    FieldMapa1.getText(), TelefonoEscenario1.getText(), BoxCiudad1.getSelectedItem().toString());
            JOptionPane.showMessageDialog((Component)null,
				"el escenario fue midificado exitosamente", "Exito",JOptionPane.INFORMATION_MESSAGE);
            NombreEscenario1.setText("");
            BoxCiudad1.removeAllItems();
            DireccionEscenario1.setText("");
            TelefonoEscenario1.setText("");
            FieldMapa1.setText("");
            jButton1.setEnabled(false);

        } catch (Exception ex) {
            Logger.getLogger(PAdminescenario.class.getName()).log(Level.SEVERE, null, ex);
        }


    


}//GEN-LAST:event_jButton1ActionPerformed




    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox BoxCiudad;
    private javax.swing.JComboBox BoxCiudad1;
    private javax.swing.JComboBox BoxCiudad2;
    private javax.swing.JTextField Busqueda;
    private javax.swing.JTextField DireccionEscenario;
    private javax.swing.JTextField DireccionEscenario1;
    private javax.swing.JTextField DireccionEscenario2;
    private javax.swing.JTextField Eliminar;
    private javax.swing.JTextField FieldMapa;
    private javax.swing.JTextField FieldMapa1;
    private javax.swing.JTextField FieldMapa2;
    private javax.swing.JTextField NombreEscenario;
    private javax.swing.JTextField NombreEscenario1;
    private javax.swing.JTextField NombreEscenario2;
    private javax.swing.JTextField TelefonoEscenario;
    private javax.swing.JTextField TelefonoEscenario1;
    private javax.swing.JTextField TelefonoEscenario2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBuscarEditarEscenario;
    private javax.swing.JButton jButtonBuscarEliminar;
    private javax.swing.JButton jButtonRegistrarEscenario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelAspectosGenerales;
    private javax.swing.JPanel jPanelAspectosGenerales1;
    private javax.swing.JPanel jPanelAspectosGenerales2;
    private javax.swing.JPanel jPanelBusquedaEditar;
    private javax.swing.JPanel jPanelBusquedaEliminar;
    private javax.swing.JPanel jPanelEditarEscenario;
    private javax.swing.JPanel jPanelEliminarEscenario;
    private javax.swing.JPanel jPanelRegistrarEscenario;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables

}
