/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PDevolucionDinero.java
 *
 * Created on 5/11/2009, 11:44:44 AM
 */

package presentacion;

import DAO.exceptions.NonexistentEntityException;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import control.DevolucionDinero;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author alirio
 */
public class PDevolucionDinero extends javax.swing.JFrame {

    private PVendedor parent;
    private DevolucionDinero devolver;
    List<String> cancelist = new ArrayList<String>();
    List<String> preslist = new ArrayList<String>();
    List<String> idlist = new ArrayList<String>();
    List<String> listreg = new ArrayList<String>();
    List<String> loclist = new ArrayList<String>();
    private int idevento=0, idpresentacion=0,idrow=0, cantidad=0, bench;
    private String entrada;

    /** Creates new form PDevolucionDinero */
    public PDevolucionDinero(PVendedor parent) {
        initComponents();

        /*Aqui se muestran en l a tabla todos los eventos cancelados con cada una de sus presentaciones*/
        devolver = new DevolucionDinero();
        cancelist = devolver.getcancelevents("Cancelado");
        int a = cancelist.size();

        if(a != 0){
            int h=0;
            int z=0;
            int m =0;
            DefaultTableModel temp = (DefaultTableModel) eventosCancelados.getModel();

            for (int i=0; i<(a/2); i++){
                int numero = Integer.parseInt(cancelist.get(h));
                preslist = devolver.getpresentation(numero);
                int sizex = preslist.size();
                int y = sizex;
                sizex = sizex - z;
                //System.out.print(sizex);
                for(int j=0; j<sizex; j++){
                    Object nuevo[]= {cancelist.get(h+1),preslist.get(m)};
                    idevento = Integer.parseInt(cancelist.get(h));
                    temp.addRow(nuevo);
                    m++;
                }
                z=y;
                h=h+2;
                idlist = devolver.getpresentationid(numero);
            }
        }

        this.getContentPane().setBackground(Color.white);
        this.parent=parent;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEventos = new javax.swing.JPanel();
        panelTabla = new javax.swing.JScrollPane();
        eventosCancelados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        doctext = new javax.swing.JTextField();
        panelDetallesCompra = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        totalPagado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        valorADevolver = new javax.swing.JTextField();
        panelLocaciones = new javax.swing.JScrollPane();
        listaLocaciones = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cantidadBoletas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        valorBoleta = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        valorAportado = new javax.swing.JTextField();
        registrarDevolucion = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fechabox = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Devolucion de Dinero");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelEventos.setBackground(new java.awt.Color(255, 255, 255));
        panelEventos.setBorder(javax.swing.BorderFactory.createTitledBorder("Eventos cancelados"));

        eventosCancelados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Evento", "Presentacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        eventosCancelados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        eventosCancelados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventosCanceladosMouseClicked(evt);
            }
        });
        panelTabla.setViewportView(eventosCancelados);
        eventosCancelados.getColumnModel().getColumn(0).setMaxWidth(190);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 3, 13));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Seleccione un Evento Cancelado");

        javax.swing.GroupLayout panelEventosLayout = new javax.swing.GroupLayout(panelEventos);
        panelEventos.setLayout(panelEventosLayout);
        panelEventosLayout.setHorizontalGroup(
            panelEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEventosLayout.createSequentialGroup()
                .addGroup(panelEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEventosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                    .addGroup(panelEventosLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        panelEventosLayout.setVerticalGroup(
            panelEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEventosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLabel2.setText("Documento del cliente:");

        doctext.setEditable(false);
        doctext.setFont(new java.awt.Font("DejaVu Sans", 3, 13));
        doctext.setForeground(new java.awt.Color(0, 16, 255));

        panelDetallesCompra.setBackground(new java.awt.Color(255, 255, 255));
        panelDetallesCompra.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles de compra"));

        jLabel3.setText("Total pagado:");

        jLabel14.setText("$");

        totalPagado.setEditable(false);
        totalPagado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel4.setText("Valor a devolver:");

        jLabel15.setText("$");

        valorADevolver.setEditable(false);
        valorADevolver.setFont(new java.awt.Font("DejaVu Sans", 3, 14));
        valorADevolver.setForeground(new java.awt.Color(255, 0, 0));
        valorADevolver.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        listaLocaciones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaLocaciones.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaLocacionesValueChanged(evt);
            }
        });
        panelLocaciones.setViewportView(listaLocaciones);

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 3, 13));
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Locaciones:");

        jLabel6.setText("Informacion de boletas:");

        jLabel7.setText("Según la locacion seleccionada");

        cantidadBoletas.setEditable(false);

        jLabel8.setText("Cantidad comprada:");

        jLabel9.setText("Valor de la boleta:");

        valorBoleta.setEditable(false);

        total.setEditable(false);

        jLabel10.setText("Total a pagar:");

        jLabel11.setText("Valor aportado:");

        valorAportado.setEditable(false);

        registrarDevolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/add.gif"))); // NOI18N
        registrarDevolucion.setText("Registrar devolución");
        registrarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarDevolucionActionPerformed(evt);
            }
        });

        jLabel16.setText("$");

        jLabel17.setText("$");

        jLabel18.setText("$");

        jLabel12.setText("Fecha Compra:");

        fechabox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fechaboxItemStateChanged(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("DejaVu Sans", 3, 13));
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("Seleccione");

        javax.swing.GroupLayout panelDetallesCompraLayout = new javax.swing.GroupLayout(panelDetallesCompra);
        panelDetallesCompra.setLayout(panelDetallesCompraLayout);
        panelDetallesCompraLayout.setHorizontalGroup(
            panelDetallesCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesCompraLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(panelDetallesCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addGroup(panelDetallesCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetallesCompraLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorADevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDetallesCompraLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetallesCompraLayout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(registrarDevolucion)
                .addGap(18, 18, 18))
            .addGroup(panelDetallesCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetallesCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(panelLocaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGroup(panelDetallesCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetallesCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelDetallesCompraLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(panelDetallesCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelDetallesCompraLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel8)
                                .addGroup(panelDetallesCompraLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetallesCompraLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelDetallesCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(valorAportado, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(total)
                                .addComponent(valorBoleta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(cantidadBoletas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(19, 19, 19))
                        .addGroup(panelDetallesCompraLayout.createSequentialGroup()
                            .addGap(102, 102, 102)
                            .addComponent(jLabel6)
                            .addContainerGap()))
                    .addGroup(panelDetallesCompraLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel7)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetallesCompraLayout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechabox, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        panelDetallesCompraLayout.setVerticalGroup(
            panelDetallesCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesCompraLayout.createSequentialGroup()
                .addGroup(panelDetallesCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(fechabox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(panelDetallesCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDetallesCompraLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetallesCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetallesCompraLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12)
                        .addGroup(panelDetallesCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(valorBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDetallesCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(cantidadBoletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDetallesCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDetallesCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valorAportado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel11)))
                    .addComponent(panelLocaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panelDetallesCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(totalPagado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDetallesCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(valorADevolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(registrarDevolucion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/salir.gif"))); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/search.gif"))); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(doctext, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelDetallesCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(doctext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelDetallesCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salir)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        parent.setVisible(true);
    }//GEN-LAST:event_salirActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
// TODO add your handling code here:
        //doctext.setText("");
        listaLocaciones.setModel(new DefaultListModel());
        fechabox.removeAllItems();
        valorBoleta.setText("");
        cantidadBoletas.setText("");
        total.setText("");
        valorAportado.setText("");
        totalPagado.setText("");
        valorADevolver.setText("");
        listaLocaciones.removeAll();

        fechabox.removeAllItems();
        devolver = new DevolucionDinero();

            String evento = eventosCancelados.getValueAt(idrow, 0).toString();
            entrada = doctext.getText();
            listreg = devolver.getregistro(doctext.getText(), evento, Integer.parseInt(idlist.get(idrow)));
            int t = listreg.size();
            int m=0;

            if(t!=0){
                for(int i=0; i<(t/3); i++){
                    fechabox.addItem(listreg.get(m+1));
                    m=m+3;
                }
            }
            else
            {fechabox.removeAllItems();}
            /*este es para probar lo que mete en el jcombobox!!!
            int y = idlist.size();
            for(int u=0; u<y;u++){
                //System.out.print("ff" + idlist.get(u));
            } */
            listaLocaciones.setSelectedIndex(0);
    }//GEN-LAST:event_buscarActionPerformed

    private void fechaboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fechaboxItemStateChanged
// TODO add your handling code here:

        valorBoleta.setText("");
        cantidadBoletas.setText("");
        total.setText("");
        valorAportado.setText("");
        totalPagado.setText("");
        valorADevolver.setText("");

        if (evt.getStateChange()== ItemEvent.SELECTED){

            DefaultListModel model = new DefaultListModel();
            int l=0;

            l = fechabox.getSelectedIndex();
            //System.out.print("Seleccion" + l);
            //System.out.print("sdfsdf"+l);
            int k=l*3;
            l = Integer.parseInt(listreg.get(l*3));
            cantidad=0;
            cantidad=k+2;
            loclist = devolver.getlocaciones(l);
            model.addElement("--------------");
            model.addElement(loclist.get(0));
            //model.addElement("two");
            //model.addElement("three");
            //model.addElement("four");
            listaLocaciones.setModel(model);
            bench=0;
            bench = fechabox.getSelectedIndex()*3;
        }
    }//GEN-LAST:event_fechaboxItemStateChanged

    private void listaLocacionesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaLocacionesValueChanged
        // TODO add your handling code here:

        int g = listaLocaciones.getSelectedIndex();
        //System.out.print("eeee"+g);
        if(g==1){
            valorBoleta.setText(loclist.get(1));
            cantidadBoletas.setText(listreg.get(cantidad));
            double totalb = new Double(valorBoleta.getText()).doubleValue();
            double totalc = new Double(cantidadBoletas.getText()).doubleValue();
            double gg = totalb * totalc;
            String jj = Double.toString(gg);
            total.setText(jj);
            valorAportado.setText(loclist.get(2));
            totalPagado.setText(loclist.get(2));
            valorADevolver.setText(loclist.get(2));
        }
        else{
            valorBoleta.setText("");
            cantidadBoletas.setText("");
            total.setText("");
            valorAportado.setText("");
            totalPagado.setText("");
            valorADevolver.setText("");
        }
    }//GEN-LAST:event_listaLocacionesValueChanged

    private void registrarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarDevolucionActionPerformed
        // TODO add your handling code here:

        int ans =  JOptionPane.showConfirmDialog((Component)null,"¿Esta seguro de que desea devolver ese dinero?", "Confirmacion",JOptionPane.YES_NO_OPTION);
        if (ans == JOptionPane.YES_OPTION) {
            devolver = new DevolucionDinero();
            try {
                devolver.destroyboletaregventa(bench);
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(PDevolucionDinero.class.getName()).log(Level.SEVERE, null, ex);
            }

            double totalb = new Double(valorADevolver.getText()).doubleValue();
            int g = eventosCancelados.getSelectedRow();
            DefaultTableModel temp = (DefaultTableModel) eventosCancelados.getModel();
            String h = temp.getValueAt(g, 0).toString();

            devolver.setremuneracion(entrada, h, totalb);

            JOptionPane.showMessageDialog((Component)null,
				"Se ha realizado la devolucion con exito", "Exito",JOptionPane.WARNING_MESSAGE);

            doctext.setEditable(true);
            doctext.setText("");
            listaLocaciones.setModel(new DefaultListModel());
            fechabox.removeAllItems();
            valorBoleta.setText("");
            cantidadBoletas.setText("");
            total.setText("");
            valorAportado.setText("");
            totalPagado.setText("");
            valorADevolver.setText("");
            listaLocaciones.removeAll();
        }
    }//GEN-LAST:event_registrarDevolucionActionPerformed


    private void eventosCanceladosMouseClicked(java.awt.event.MouseEvent evt) {                                               
        // TODO add your handling code here:
        idrow = eventosCancelados.getSelectedRow();
        //System.out.print("ssss" + idrow);
        doctext.setEditable(true);
        doctext.setText("");
        listaLocaciones.setModel(new DefaultListModel());
        fechabox.removeAllItems();
        valorBoleta.setText("");
        cantidadBoletas.setText("");
        total.setText("");
        valorAportado.setText("");
        totalPagado.setText("");
        valorADevolver.setText("");
        listaLocaciones.removeAll();
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JTextField cantidadBoletas;
    private javax.swing.JTextField doctext;
    private javax.swing.JTable eventosCancelados;
    private javax.swing.JComboBox fechabox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList listaLocaciones;
    private javax.swing.JPanel panelDetallesCompra;
    private javax.swing.JPanel panelEventos;
    private javax.swing.JScrollPane panelLocaciones;
    private javax.swing.JScrollPane panelTabla;
    private javax.swing.JButton registrarDevolucion;
    private javax.swing.JButton salir;
    private javax.swing.JTextField total;
    private javax.swing.JTextField totalPagado;
    private javax.swing.JTextField valorADevolver;
    private javax.swing.JTextField valorAportado;
    private javax.swing.JTextField valorBoleta;
    // End of variables declaration//GEN-END:variables

}
