/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * principal.java
 *
 * Created on Oct 12, 2009, 7:32:03 PM
 */

package presentacion;
import control.ValidarIngreso;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author alirio
 */
public class PLogin extends javax.swing.JFrame {

    private ValidarIngreso validar;
    private PAbout about;
    private PRegistro reg;
    private PAdministrador admin;
    private PVendedor venta;



    /** Creates new form principal */
    public PLogin() {


        initComponents();
        this.setSize(720, 500);
        this.setLocationRelativeTo(null);
        PFondoLogin fondo=new PFondoLogin();
        this.add(fondo,BorderLayout.CENTER);
        this.pack();
        this.getContentPane().setBackground(Color.WHITE);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        botoningreso = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        textocontrasena = new javax.swing.JPasswordField();
        jLabel25 = new javax.swing.JLabel();
        textousuario = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIBO (Sistema de Informacion de Boleteria)");
        setBackground(new java.awt.Color(208, 142, 76));
        setBounds(new java.awt.Rectangle(300, 300, 0, 0));
        setResizable(false);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/sibo.jpg"))); // NOI18N

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/boleteria.jpg"))); // NOI18N

        jLabel28.setText("Todos los derechos Reservados.");

        jLabel27.setText("Dacaf Systems 2009");

        jLabel1.setFont(new java.awt.Font("eufm10", 3, 36));
        jLabel1.setForeground(new java.awt.Color(117, 46, 53));
        jLabel1.setText("MiBoleta.Com");

        botoningreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/enter.gif"))); // NOI18N
        botoningreso.setText("Ingresar");
        botoningreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoningresoActionPerformed(evt);
            }
        });

        textocontrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textocontrasenaKeyPressed(evt);
            }
        });

        jLabel25.setText("Contraseña");

        textousuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textousuarioKeyPressed(evt);
            }
        });

        jLabel24.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 3, 18));
        jLabel2.setText("Identificación:");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans Light", 3, 24));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/dacaf.jpg"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        menu2.setText("About");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/salir.gif"))); // NOI18N
        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu2.add(jMenuItem1);

        jMenuBar1.add(menu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel24)
                        .addComponent(jLabel25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textocontrasena, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textousuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botoningreso, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel3))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textocontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botoningreso))
                    .addComponent(jLabel26))
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        about = new PAbout();
        about.setVisible(true);
}//GEN-LAST:event_jMenuItem1ActionPerformed

    private void botoningresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoningresoActionPerformed
        // TODO add your handling code here:
        validar=new ValidarIngreso();

        String user = textousuario.getText();
        String pass = textocontrasena.getText();
        if (user.length()>0 && pass.length()>0){
            if (validar.validarIngreso(user, pass)){
                if (validar.getRol().equals("Administrador")){
                    this.setVisible(false);
                    admin = new PAdministrador(this);
                    admin.setVisible(true);
                }
                else{
                    this.setVisible(false);
                    venta = new PVendedor(this);
                    venta.setVisible(true);
                }
            }
            else
                
                JOptionPane.showMessageDialog(null, "Los datos ingresados no son validos");
        }
        else
            
            JOptionPane.showMessageDialog(null, "Debe ingresar un usuario y una contraseña");
        
}//GEN-LAST:event_botoningresoActionPerformed

    private void textocontrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textocontrasenaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            botoningreso.doClick();
    }//GEN-LAST:event_textocontrasenaKeyPressed


    private void textousuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textousuarioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            textousuario.transferFocus();
    }//GEN-LAST:event_textousuarioKeyPressed

    public void setTextoContrasena(String texto){
        textocontrasena.setText(texto);
    }

    public void setTextoUsuario(String texto){
        textousuario.setText(texto);
        textousuario.requestFocus();
    }

    public String getTextoUsuario(){
        return textousuario.getText();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoningreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JMenu menu2;
    private javax.swing.JPasswordField textocontrasena;
    private javax.swing.JTextField textousuario;
    // End of variables declaration//GEN-END:variables

}
