/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * vendedor.java
 *
 * Created on Oct 27, 2009, 9:40:28 PM
 */

package presentacion;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author alirio
 */
public class PVendedor extends javax.swing.JFrame {

    private PLogin parent;

    /** Creates new form vendedor */
    public PVendedor(PLogin parent) {
        initComponents();
        this.setSize(655, 452);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        this.parent=parent;
        usuario.setText(parent.getTextoUsuario());
        PFondovendedor fondo=new PFondovendedor();
        this.add(fondo,BorderLayout.CENTER);
        this.pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        venderBoleta = new javax.swing.JButton();
        cancelarReserva = new javax.swing.JButton();
        devolverDinero = new javax.swing.JButton();
        entregarBoleta = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        rol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Vendedor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        venderBoleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/ticket.gif"))); // NOI18N
        venderBoleta.setText("Vender Boleta");
        venderBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderBoletaActionPerformed(evt);
            }
        });

        cancelarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/blender.gif"))); // NOI18N
        cancelarReserva.setText("Cancelar Reserva");
        cancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarReservaActionPerformed(evt);
            }
        });

        devolverDinero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/delete.gif"))); // NOI18N
        devolverDinero.setText("Devolver Dinero");
        devolverDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverDineroActionPerformed(evt);
            }
        });

        entregarBoleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/event.gif"))); // NOI18N
        entregarBoleta.setText("Entrega Boleta");
        entregarBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entregarBoletaActionPerformed(evt);
            }
        });

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/salir.gif"))); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/sibo.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel2.setText("Opciones de ventas");

        jLabel3.setForeground(new java.awt.Color(153, 204, 255));
        jLabel3.setText("Usuario:");

        jLabel4.setForeground(new java.awt.Color(153, 204, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/Dibujo.GIF"))); // NOI18N
        jLabel4.setText("Rol:");

        usuario.setText("nombre");

        rol.setText("Vendedor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rol)
                                    .addComponent(usuario))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cancelarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(devolverDinero, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(venderBoleta, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(entregarBoleta, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(usuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rol)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(venderBoleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(devolverDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entregarBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(salir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        parent.setTextoUsuario("");
        parent.setTextoContrasena("");
        parent.setVisible(true);
    }//GEN-LAST:event_salirActionPerformed

    private void venderBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderBoletaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        PVentaBoleta venta=new PVentaBoleta(this);
        venta.setLocationRelativeTo(null);
        venta.setVisible(true);
    }//GEN-LAST:event_venderBoletaActionPerformed

    private void cancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarReservaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        PCancelacionReserva cancelacion=new PCancelacionReserva(this);
        cancelacion.setLocationRelativeTo(null);
        cancelacion.setVisible(true);
    }//GEN-LAST:event_cancelarReservaActionPerformed

    private void devolverDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverDineroActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        PDevolucionDinero devolucion=new PDevolucionDinero(this);
        devolucion.setLocationRelativeTo(null);
        devolucion.setVisible(true);
    }//GEN-LAST:event_devolverDineroActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int confirmado=JOptionPane.showConfirmDialog(this, "Esta acción cerrará la sesión activa\n¿Seguro que desea continuar?\n\n", "¿Cerrar Sesión?", JOptionPane.YES_NO_OPTION);
        if(confirmado==JOptionPane.YES_OPTION){
            parent.setTextoUsuario("");
            parent.setTextoContrasena("");
            parent.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_formWindowClosing

    private void entregarBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entregarBoletaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        PEntregaBoleta entrega=new PEntregaBoleta(this);
        entrega.setLocationRelativeTo(null);
        entrega.setVisible(true);
    }//GEN-LAST:event_entregarBoletaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarReserva;
    private javax.swing.JButton devolverDinero;
    private javax.swing.JButton entregarBoleta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel rol;
    private javax.swing.JButton salir;
    private javax.swing.JLabel usuario;
    private javax.swing.JButton venderBoleta;
    // End of variables declaration//GEN-END:variables

    public String getUsuario() {
        return usuario.getText();
    }


}
